version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db

  db:
    image: postgres:16.1
    restart: on-failure
    env_file: ./.env
    ports:
      - ${DB_PORT}:${DB_PORT}